import { Roboto } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import {AppProvider} from '../components/AppContext'
import { EdgeStoreProvider } from '../../lib/edgeStore'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
       <EdgeStoreProvider>
        <main className=' max-w-6xl mx-auto p-4' >
         <AppProvider>
          <Header /> 
          {children}
          <Footer />
         </AppProvider>
        </main>
      </EdgeStoreProvider> 
      </body>
    </html>
  )
}
